export const ADD_CART_ITEM_REQUEST = "ADD_CART_ITEM_REQUEST";

export const ADD_CART_ITEM_SUCCESS = "ADD_CART_ITEM_SUCCESS";

export const ADD_CART_ITEM_FAIL = "ADD_CART_ITEM_FAIL";

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";

export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";

export const DELETE_CART_ITEM_FAIL = "DELETE_CART_ITEM_FAIL";

export const SHIPPING_INFO_REQUEST = "SHIPPING_INFO_REQUEST";

export const SHIPPING_INFO_SUCCESS = "SHIPPING_INFO_SUCCESS";

export const SHIPPING_INFO_FAIL = "SHIPPING_INFO_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
