export const ALL_RESTAURANT_REQUEST = "ALL_RESTAURANT_REQUEST";

export const ALL_RESTAURANT_SUCCESS = "ALL_RESTAURANT_SUCCESS";

export const ALL_RESTAURANT_FAIL = "ALL_RESTAURANT_FAIL";

export const RESTAURANT_DETAILS_REQUEST = "RESTAURANT_DETAILS_REQUEST";

export const RESTAURANT_DETAILS_SUCCESS = "RESTAURANT_DETAILS_SUCCESS";

export const RESTAURANT_DETAILS_FAIL = "RESTAURANT_DETAILS_FAIL";

export const ADD_RESTAURANT_REQUEST = "ADD_RESTAURANT_REQUEST";

export const ADD_RESTAURANT_SUCCESS = "ADD_RESTAURANT_SUCCESS";

export const ADD_RESTAURANT_FAIL = "ADD_RESTAURANT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
